/*--------------------------------------------------------------------------*/
/* Copyright 2020-2022 NXP                                                  */
/*                                                                          */
/* NXP Confidential. This software is owned or controlled by NXP and may    */
/* only be used strictly in accordance with the applicable license terms.   */
/* By expressly accepting such terms or by downloading, installing,         */
/* activating and/or otherwise using the software, you are agreeing that    */
/* you have read, and that you agree to comply with and are bound by, such  */
/* license terms. If you do not agree to be bound by the applicable license */
/* terms, then you may not retain, install, activate or otherwise use the   */
/* software.                                                                */
/*--------------------------------------------------------------------------*/

/**
 * @file  mcuxClEcc_Internal.h
 * @brief internal header of mcuxClEcc functionalities
 */


#ifndef MCUXCLECC_INTERNAL_H_
#define MCUXCLECC_INTERNAL_H_

#include <mcuxClConfig.h> // Exported features flags header
#include <mcuxClSession.h>
#include <mcuxClPkc_Functions.h>
#include <mcuxClEcc_Types.h>


/**
 * Generic ECC PKC workarea memory layout.
 */
#define ECC_P    0x00u
#define ECC_N    0x01u
#define ECC_ONE  0x02u
#define ECC_ZERO 0x03u

#define ECC_V0   0x04u
#define ECC_V1   0x05u
#define ECC_V2   0x06u
#define ECC_V3   0x07u
#define ECC_V4   0x08u
#define ECC_V5   0x09u
#define ECC_V6   0x0Au
#define ECC_V7   0x0Bu
#define ECC_V8   0x0Cu
#define ECC_V9   0x0Du
#define ECC_VA   0x0Eu
#define ECC_VB   0x0Fu

#define ECC_PS     0x10u
#define ECC_NS     0x11u
#define ECC_CP0    0x12u
#define ECC_CP1    0x13u
#define ECC_PFULL  0x14u
#define ECC_NFULL  0x15u
#define ECC_PQSQR  0x16u
#define ECC_NQSQR  0x17u

#define ECC_S0  0x18u
#define ECC_T0  0x19u
#define ECC_S1  0x1Au
#define ECC_T1  0x1Bu
#define ECC_S2  0x1Cu
#define ECC_T2  0x1Du
#define ECC_S3  0x1Eu
#define ECC_T3  0x1Fu

#define ECC_COORD00  0x20u
#define ECC_COORD01  0x21u
#define ECC_COORD02  0x22u
#define ECC_COORD03  0x23u
#define ECC_COORD04  0x24u
#define ECC_COORD05  0x25u
#define ECC_COORD06  0x26u
#define ECC_COORD07  0x27u
#define ECC_COORD08  0x28u
#define ECC_COORD09  0x29u
#define ECC_COORD10  0x2Au
#define ECC_COORD11  0x2Bu
#define ECC_COORD12  0x2Cu
#define ECC_COORD13  0x2Du
#define ECC_COORD14  0x2Eu
#define ECC_COORD15  0x2Fu
#define ECC_COORD16  0x30u
#define ECC_COORD17  0x31u
#define ECC_COORD18  0x32u
#define ECC_COORD19  0x33u
#define ECC_COORD20  0x34u
#define ECC_COORD21  0x35u
#define ECC_COORD22  0x36u
#define ECC_COORD23  0x37u
#define ECC_COORD24  0x38u
#define ECC_COORD25  0x39u
#define ECC_COORD26  0x3Au
#define ECC_COORD27  0x3Bu

#define ECC_NO_OF_VIRTUALS  ECC_PS

/**
 * Constants for the length of curve parameters.
 */

/* Definition for curve25519 curve */
#define MCUXCLECC_MONTDH_CURVE25519_SIZE_PRIMEP          (32U)
#define MCUXCLECC_MONTDH_CURVE25519_SIZE_BASEPOINTORDER  (32U)
#define MCUXCLECC_MONTDH_CURVE25519_SIZE_PRIVATEKEY      (MCUXCLECC_MONTDH_CURVE25519_SIZE_BASEPOINTORDER)
#define MCUXCLECC_MONTDH_CURVE25519_SIZE_PUBLICKEY       (MCUXCLECC_MONTDH_CURVE25519_SIZE_PRIMEP)
#define MCUXCLECC_MONTDH_CURVE25519_SIZE_SHAREDSECRET    (MCUXCLECC_MONTDH_CURVE25519_SIZE_PRIMEP)

/* Definition for curve448 curve */
#define MCUXCLECC_MONTDH_CURVE448_SIZE_PRIMEP            (56U)
#define MCUXCLECC_MONTDH_CURVE448_SIZE_BASEPOINTORDER    (56U)
#define MCUXCLECC_MONTDH_CURVE448_SIZE_PRIVATEKEY        (MCUXCLECC_MONTDH_CURVE448_SIZE_BASEPOINTORDER)
#define MCUXCLECC_MONTDH_CURVE448_SIZE_PUBLICKEY         (MCUXCLECC_MONTDH_CURVE448_SIZE_PRIMEP)
#define MCUXCLECC_MONTDH_CURVE448_SIZE_SHAREDSECRET      (MCUXCLECC_MONTDH_CURVE448_SIZE_PRIMEP)



/* Definition for secp160k1 curve */
#define MCUXCLECC_WEIERECC_SECP160K1_SIZE_PRIMEP            (20U)
#define MCUXCLECC_WEIERECC_SECP160K1_SIZE_BASEPOINTORDER    (21U)
#define MCUXCLECC_WEIERECC_SECP160K1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_SECP160K1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP160K1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_SECP160K1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP160K1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_SECP160K1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP160K1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_SECP160K1_SIZE_BASEPOINTORDER)

/* Definition for secp192k1 curve */
#define MCUXCLECC_WEIERECC_SECP192K1_SIZE_PRIMEP            (24U)
#define MCUXCLECC_WEIERECC_SECP192K1_SIZE_BASEPOINTORDER    (24U)
#define MCUXCLECC_WEIERECC_SECP192K1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_SECP192K1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP192K1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_SECP192K1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP192K1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_SECP192K1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP192K1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_SECP192K1_SIZE_BASEPOINTORDER)

/* Definition for secp224k1 curve */
#define MCUXCLECC_WEIERECC_SECP224K1_SIZE_PRIMEP            (28U)
#define MCUXCLECC_WEIERECC_SECP224K1_SIZE_BASEPOINTORDER    (29U)
#define MCUXCLECC_WEIERECC_SECP224K1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_SECP224K1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP224K1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_SECP224K1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP224K1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_SECP224K1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP224K1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_SECP224K1_SIZE_BASEPOINTORDER)

/* Definition for secp256k1 curve */
#define MCUXCLECC_WEIERECC_SECP256K1_SIZE_PRIMEP            (32U)
#define MCUXCLECC_WEIERECC_SECP256K1_SIZE_BASEPOINTORDER    (32U)
#define MCUXCLECC_WEIERECC_SECP256K1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_SECP224K1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP256K1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_SECP224K1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP256K1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_SECP224K1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP256K1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_SECP256K1_SIZE_BASEPOINTORDER)

/* Definition for secp192r1 curve */
#define MCUXCLECC_WEIERECC_SECP192R1_SIZE_PRIMEP            (24U)
#define MCUXCLECC_WEIERECC_SECP192R1_SIZE_BASEPOINTORDER    (24U)
#define MCUXCLECC_WEIERECC_SECP192R1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_SECP192R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP192R1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_SECP192R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP192R1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_SECP192R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP192R1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_SECP192R1_SIZE_BASEPOINTORDER)

/* Definition for secp224r1 curve */
#define MCUXCLECC_WEIERECC_SECP224R1_SIZE_PRIMEP            (28U)
#define MCUXCLECC_WEIERECC_SECP224R1_SIZE_BASEPOINTORDER    (28U)
#define MCUXCLECC_WEIERECC_SECP224R1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_SECP224R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP224R1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_SECP224R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP224R1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_SECP224R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP224R1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_SECP224R1_SIZE_BASEPOINTORDER)

/* Definition for secp256r1 curve */
#define MCUXCLECC_WEIERECC_SECP256R1_SIZE_PRIMEP            (32U)
#define MCUXCLECC_WEIERECC_SECP256R1_SIZE_BASEPOINTORDER    (32U)
#define MCUXCLECC_WEIERECC_SECP256R1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_SECP256R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP256R1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_SECP256R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP256R1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_SECP256R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP256R1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_SECP256R1_SIZE_BASEPOINTORDER)

/* Definition for secp384r1 curve */
#define MCUXCLECC_WEIERECC_SECP384R1_SIZE_PRIMEP            (48U)
#define MCUXCLECC_WEIERECC_SECP384R1_SIZE_BASEPOINTORDER    (48U)
#define MCUXCLECC_WEIERECC_SECP384R1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_SECP384R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP384R1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_SECP384R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP384R1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_SECP384R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP384R1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_SECP384R1_SIZE_BASEPOINTORDER)

/* Definition for secp521r1 curve */
#define MCUXCLECC_WEIERECC_SECP521R1_SIZE_PRIMEP            (66U)
#define MCUXCLECC_WEIERECC_SECP521R1_SIZE_BASEPOINTORDER    (66U)
#define MCUXCLECC_WEIERECC_SECP521R1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_SECP521R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_SECP521R1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_SECP521R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP521R1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_SECP521R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_SECP521R1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_SECP521R1_SIZE_BASEPOINTORDER)

/* Definition for brainpoolP160r1 curve */
#define MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_PRIMEP            (20U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_BASEPOINTORDER    (20U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP160R1_SIZE_BASEPOINTORDER)

/* Definition for brainpoolP192r1 curve */
#define MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_PRIMEP            (24U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_BASEPOINTORDER    (24U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP192R1_SIZE_BASEPOINTORDER)

/* Definition for brainpoolP224r1 curve */
#define MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_PRIMEP            (28U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_BASEPOINTORDER    (28U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP224R1_SIZE_BASEPOINTORDER)

/* Definition for brainpoolP256r1 curve */
#define MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_PRIMEP            (32U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_BASEPOINTORDER    (32U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP256R1_SIZE_BASEPOINTORDER)

/* Definition for brainpoolP320r1 curve */
#define MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_PRIMEP            (40U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_BASEPOINTORDER    (40U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP320R1_SIZE_BASEPOINTORDER)

/* Definition for brainpoolP320r1 curve */
#define MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_PRIMEP            (48U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_BASEPOINTORDER    (48U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP384R1_SIZE_BASEPOINTORDER)

/* Definition for brainpoolP512r1 curve */
#define MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_PRIMEP            (64U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_BASEPOINTORDER    (64U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP512R1_SIZE_BASEPOINTORDER)

/* Definition for brainpoolP160t1 curve */
#define MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_PRIMEP            (20U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_BASEPOINTORDER    (20U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP160T1_SIZE_BASEPOINTORDER)

/* Definition for brainpoolP192t1 curve */
#define MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_PRIMEP            (24U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_BASEPOINTORDER    (24U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP192T1_SIZE_BASEPOINTORDER)

/* Definition for brainpoolP224t1 curve */
#define MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_PRIMEP            (28U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_BASEPOINTORDER    (28U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP224T1_SIZE_BASEPOINTORDER)

/* Definition for brainpoolP256t1 curve */
#define MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_PRIMEP            (32U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_BASEPOINTORDER    (32U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP256T1_SIZE_BASEPOINTORDER)

/* Definition for brainpoolP320t1 curve */
#define MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_PRIMEP            (40U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_BASEPOINTORDER    (40U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP320T1_SIZE_BASEPOINTORDER)

/* Definition for brainpoolP384t1 curve */
#define MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_PRIMEP            (48U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_BASEPOINTORDER    (48U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP384T1_SIZE_BASEPOINTORDER)

/* Definition for brainpoolP512t1 curve */
#define MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_PRIMEP            (64U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_BASEPOINTORDER    (64U)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_BRAINPOOLP512T1_SIZE_BASEPOINTORDER)

/* Definition max for ECC curves (ECC component officially supports up to 640 bit curves) */
#define MCUXCLECC_WEIERECC_MAX_SIZE_PRIMEP            (80U)
#define MCUXCLECC_WEIERECC_MAX_SIZE_BASEPOINTORDER    (80U)
#define MCUXCLECC_WEIERECC_MAX_SIZE_PRIVATEKEY        (MCUXCLECC_WEIERECC_MAX_SIZE_BASEPOINTORDER)
#define MCUXCLECC_WEIERECC_MAX_SIZE_PUBLICKEY         (2U * MCUXCLECC_WEIERECC_MAX_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_MAX_SIZE_SHAREDSECRET      (MCUXCLECC_WEIERECC_MAX_SIZE_PRIMEP)
#define MCUXCLECC_WEIERECC_MAX_SIZE_SIGNATURE         (2U * MCUXCLECC_WEIERECC_MAX_SIZE_BASEPOINTORDER)

/**
 * CPU workarea layout of ECC APIs.
 */
typedef struct
{
    uint32_t wordNumCpuWa;  /* number of words (uint32_t) used in CPU workarea */
    uint32_t wordNumPkcWa;  /* number of words (uint32_t) used in PKC workarea */
    mcuxClPkc_State_t pkcStateBackup;
    uint32_t pOperands32[];
} mcuxClEcc_CpuWa_t;

typedef struct mcuxClEcc_CommonDomainParams mcuxClEcc_CommonDomainParams_t;


/**
 * The scalar multiplication function signatures.
 */
typedef MCUX_CSSL_FP_PROTECTED_TYPE(mcuxClEcc_Status_t) (*mcuxClEcc_ScalarMultFunction_t)(
    mcuxClSession_Handle_t pSession,                ///< Handle for the current CL session
    mcuxClEcc_CommonDomainParams_t *pDomainParams,  ///< Pointer to ECC domain parameters structure
    uint8_t iScalar,                               ///< Pointer table index of scalar buffer in PKC RAM
    uint32_t scalarBitLength,                      ///< Bit length of the scalar
    uint32_t options                               ///< Parameter to pass options
    );


/**
 * Common part of domain parameter structure, shared by all ECC functions.
 */
struct mcuxClEcc_CommonDomainParams
{
    uint16_t byteLenP;       ///< byte length of prime p
    uint16_t byteLenN;       ///< byte length of base point order n
    uint8_t *pFullModulusP;  ///< pointer to p'||p (in little endian format)
    uint8_t *pFullModulusN;  ///< pointer to n'||n (in little endian format)
    uint8_t *pR2P;           ///< pointer to Montgomery parameter R^2 mod p (in little endian format)
    uint8_t *pR2N;           ///< pointer to Montgomery parameter R^2 mod n (in little endian format)
    uint8_t *pCurveParam1;   ///< Pointer to first curve parameter (a for Weierstrass and twisted Edwards curves and A for Montgomery curves)
    uint8_t *pCurveParam2;   ///< Pointer to second curve parameter (b for Weierstrass curves, d for twisted Edwards curves and B for Montgomery curves)
    uint8_t *pGx;            ///< Pointer to x-coordinate Gx of base point G
    uint8_t *pGy;            ///< Pointer to y-coordinate Gy of base point G
    uint8_t *pPrecPoints;    ///< Pointer to pre-computed points for fixed base point scalar multiplication (2^(byteLenN * 4) * G for Weierstrass curves, used in ECDSA signature verification; reserved for other curves)
    mcuxClEcc_ScalarMultFunction_t pSecFixScalarMultFct;    ///< Pointer to secure scalar multiplication function that shall be used to perform a scalar multiplication lambda*G for secret scalar lambda in {1,...,n-1} and base point G
    mcuxClEcc_ScalarMultFunction_t pSecVarScalarMultFct;    ///< Pointer to secure scalar multiplication function that shall be used to perform a scalar multiplication lambad*P for secret scalar lambda in {1,...,n-1} and arbitrary point P on the curve
    mcuxClEcc_ScalarMultFunction_t pPlainFixScalarMultFct;  ///< Pointer to plain scalar multiplication function that shall be used to perform a scalar multiplication lambda*G for non-secret scalar lambda in {1,...,n-1} and base point G
    mcuxClEcc_ScalarMultFunction_t pPlainVarScalarMultFct;  ///< Pointer to plain scalar multiplication function that shall be used to perform a scalar multiplication lambda*G for non-secret scalar lambda in {1,...,n-1} and arbitrary point P on the curve
};


#define MCUXCLECC_ALIGNED_SIZE(byteLength)  \
    ((((byteLength) + (sizeof(uint32_t)) - 1u) / (sizeof(uint32_t))) * (sizeof(uint32_t)))


MCUX_CSSL_FP_FUNCTION_DECL(mcuxClEcc_SetupEnvironment)
MCUX_CSSL_FP_PROTECTED_TYPE(mcuxClEcc_Status_t) mcuxClEcc_SetupEnvironment(
    mcuxClSession_Handle_t pSession,
    mcuxClEcc_CommonDomainParams_t *pCommonDomainParams,
    uint8_t noOfBuffers
    );


#endif /* MCUXCLECC_INTERNAL_H_ */
