/*--------------------------------------------------------------------------*/
/* Copyright 2020-2023 NXP                                                  */
/*                                                                          */
/* NXP Confidential. This software is owned or controlled by NXP and may    */
/* only be used strictly in accordance with the applicable license terms.   */
/* By expressly accepting such terms or by downloading, installing,         */
/* activating and/or otherwise using the software, you are agreeing that    */
/* you have read, and that you agree to comply with and are bound by, such  */
/* license terms. If you do not agree to be bound by the applicable license */
/* terms, then you may not retain, install, activate or otherwise use the   */
/* software.                                                                */
/*--------------------------------------------------------------------------*/

/**
 * @file  mcuxClOscca_FunctionIdentifiers.h
 * @brief Definition of function identifiers for the flow protection mechanism.
 *
 * @note This file might be post-processed to update the identifier values to
 * proper/secure values.
 */

#ifndef MCUX_OSCCACL_FLOW_PROTECTION_FUNCTION_IDENTIFIERS_H_
#define MCUX_OSCCACL_FLOW_PROTECTION_FUNCTION_IDENTIFIERS_H_

/* TODO CLNS-6644: [ARCH] add more function identifiers */
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_Cipher_init_encrypt                 (0xFFFFu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaCipherModes_finish_internal_encrypt_Sm4 (0xFFFFu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaCipherModes_finish_internal_decrypt_Sm4 (0xFFFFu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_Signature_OnlyVerify_SelfTest       (0xFFFFu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_Signature_SignVerify_SelfTest       (0xFFFFu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_Cipher_EncDec_selftest              (0xFFFFu)

#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_KeyExchange_SelfTest                (0x734Cu)       
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaMacModes_finish                         (0x2E39u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaMacModes_process                        (0x4F16u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaMacModes_compute                        (0x343Bu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaMacModes_init                           (0x7626u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaMacModes_SM4_Gen_K1K2                   (0x45ADu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaMacModes_Engine_CBCMAC_Finalize         (0x2997u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaMacModes_Engine_CMAC_Finalize           (0x46D9u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaMacModes_Engine_CBCMAC_Update           (0x55B4u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaMacModes_Engine_CMAC_Update             (0x0FB8u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaMacModes_Engine_CBCMAC_Init             (0x685Du)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaMacModes_Engine_CMAC_Init               (0x07D5u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaMacModes_Engine_CBCMAC_Oneshot          (0x38A7u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaMacModes_Engine_CMAC_Oneshot            (0x1AD9u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaRandomModes_ROtrng_reseed               (0x4E78u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaCipherModes_finish_Sm4                  (0x585Bu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaCipherModes_process_Sm4                 (0x21AFu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaCipherModes_init_decrypt_Sm4            (0x5437u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaCipherModes_init_encrypt_Sm4            (0x70F2u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaCipherModes_decrypt_Sm4                 (0x05FCu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaCipherModes_encrypt_Sm4                 (0x5AE4u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm4_FastSecureXor                       (0x5955u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm4_switch_endianness                   (0x16CDu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm3_sw_finish_sm3                       (0x655Au)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm3_sw_process_sm3                      (0x68D9u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm3_sw_oneShotSkeleton_sm3              (0x0B37u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm3_sm3_finishSkeleton                  (0x7135u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm3_sm3_processSkeleton                 (0x2BB4u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm3_sm3_oneShotSkeleton                 (0x4BC5u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaRandomModes_ROtrng_selftest             (0x6725u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaRandomModes_ROtrng_PowerOnTest          (0x0A7Du)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaRandomModes_ROtrng_DeliverySimpleTest   (0x0FA3u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaRandomModes_ROtrng_PokerTest            (0x660Fu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaRandomModes_ROtrng_generate             (0x0FE2u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaRandomModes_ROtrng_init                 (0x53A5u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaAeadModes_SkeletonCcm                   (0x707Cu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaPkc_CalcMontInverse                     (0x2D2Eu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaAeadModes_EngineCcm                     (0x6659u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaAeadModes_SM4_Crypt_Internal_Ctr        (0x4DD2u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaPkc_ComputeModInv                       (0x0FC6u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaPkc_LeadingZeros                        (0x61C7u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaPkc_MultipleShiftRotate_Index           (0x2FC4u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaPkc_GeneratePointerTable                (0x3B91u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaPkc_ComputeQSquared                     (0x4177u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaPkc_ComputeNDash                        (0x1AE5u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaPkc_StartFupProgram                     (0x16D3u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaPkc_Op                                  (0x4CC7u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaPkc_SetFupTable                         (0x03DDu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaPkc_WaitforFinish                       (0x2E55u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaPkc_GetWordSize                         (0x43B9u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaPkc_SetWordSize                         (0x46A7u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaPkc_Init                                (0x6C35u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaPkc_Reset                               (0x0CF6u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaAeadModes_init                          (0x0F27u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaAeadModes_init_encrypt                  (0x099Fu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaAeadModes_init_decrypt                  (0x5AA3u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaAeadModes_process                       (0x4973u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaAeadModes_process_adata                 (0x790Bu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaAeadModes_finish                        (0x5E0Du)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaAeadModes_verify                        (0x17D2u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaAeadModes_crypt                         (0x44DEu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaAeadModes_encrypt                       (0x69C6u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaAeadModes_decrypt                       (0x4765u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaMacModes_prepareHMACKey                 (0x5D23u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaMacModes_Engine_HMAC_Init               (0x622Fu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm4_Tprime                              (0x71A9u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm4_Lprime                              (0x7534u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm4_T                                   (0x44F9u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm4_L                                   (0x0D57u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaMacModes_Engine_HMAC_Finalize           (0x3726u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaMacModes_Engine_HMAC_Oneshot            (0x287Du)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm4_Tau                                 (0x7CC1u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaMacModes_Engine_HMAC_Update             (0x1E93u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_Cipher_SkeletonSM2                  (0x6A95u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_Cipher_finish                       (0x4DC6u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_Cipher_process                      (0x6CB8u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_Cipher_init_decrypt                 (0x237Cu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSM2_GenerateKeyPair                     (0x66A5u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_Signature_Sign                      (0x5953u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_Signature_Verify                    (0x3F30u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm3_Safo_Hash_PreLoad                   (0x297Cu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm3_Safo_Hash_Auto                      (0x562Du)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm3_Safo_Hash_Norm                      (0x37C4u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm3_SetMessagePreLoadIV_Sgi             (0x1957u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm3_ProcessMessageBlock_Sgi             (0x213Fu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_RobustCompareToZero                 (0x38E6u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_RobustCompareBoolean                (0x25F8u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_SignVerify_SelfTest                 (0x617Cu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_EncDec_SelfTest                     (0x2A2Fu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_KeyExchange                         (0x7CA4u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_Decrypt                             (0x74D8u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_Encrypt                             (0x17D1u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_ComputePrehash                      (0x472Du)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_InvertPrivateKey                    (0x6387u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_Verify                              (0x36F0u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_Sign                                (0x1B2Bu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_KeyGen                              (0x6E52u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_Export                              (0x21EBu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_Import                              (0x341Fu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_EccPointCheckCoordinate             (0x1A76u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_EccPointAddOrDouble                 (0x5F60u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_EccTransAffinePoint2Jac             (0x606Fu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_EccGenRandomBytes                   (0x153Eu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_EccPointMultMontgomery              (0x74CAu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_EccPointAdd                         (0x6353u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_EccPointDouble                      (0x60AFu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_EccPointConvert2Affine              (0x0DE9u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_EccJacPointCheck                    (0x352Du)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_EccImportInputPointYNegNoInit       (0x71E8u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_EccImportInputPointWithInit         (0x21DDu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_EccGenerateZ                        (0x5D07u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_EccPrepareParameters                (0x0FE8u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_EccInit                             (0x2BC9u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_WrapHash                            (0x65F0u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_EncDec_ExitClear                    (0x2CDCu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_ValidateEncDecCtx                   (0x4C3Bu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_EncDec_UpdatePhase                  (0x68C7u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_SecondPartOfInitPhase               (0x64D5u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_KDF                                 (0x5A59u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_FastSecureXor                       (0x71B2u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_Internal_CRC16                      (0x1EA9u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_SetParamCrcValue                    (0x5CF0u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_CheckParamCrc                       (0x4F1Cu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_CRC16                               (0x0E97u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_Cipher_decrypt                      (0x4ACBu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_Cipher_encrypt                      (0x3F18u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm2_KeyEx_ExitClear                     (0x5C4Eu)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm4_ScheduleSM4Key                      (0x3B46u)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaSm4_EngineSM4                           (0x3B2Au)
#define MCUX_CSSL_FP_FUNCID_mcuxClOsccaCipherModes_SkeletonSM4                 (0x3D38u)
#endif /* MCUX_OSCCACL_FLOW_PROTECTION_FUNCTION_IDENTIFIERS_H_ */
