/*--------------------------------------------------------------------------*/
/* Copyright 2023 NXP                                                       */
/*                                                                          */
/* NXP Confidential. This software is owned or controlled by NXP and may    */
/* only be used strictly in accordance with the applicable license terms.   */
/* By expressly accepting such terms or by downloading, installing,         */
/* activating and/or otherwise using the software, you are agreeing that    */
/* you have read, and that you agree to comply with and are bound by, such  */
/* license terms. If you do not agree to be bound by the applicable license */
/* terms, then you may not retain, install, activate or otherwise use the   */
/* software.                                                                */
/*--------------------------------------------------------------------------*/

/**
 * @file  mcuxClRandomModes_TestMode_CtrDrbg_AES256_PTG3_example.c
 * @brief Example for the mcuxClRandomModes component
 *
 * @example mcuxClRandomModes_TestMode_CtrDrbg_AES256_PTG3_example.c
 * @brief   Example for the mcuxClRandomModes component
 */

#include <mcuxClRandom.h>
#include <mcuxClRandomModes.h>
#include <mcuxClSession.h>
#include <mcuxCsslFlowProtection.h>
#include <mcuxClCore_FunctionIdentifiers.h> // Code flow protection
#include <mcuxClExample_Session_Helper.h>
#include <mcuxClCore_Examples.h>
#include <mcuxClEls.h> // Interface to the entire mcuxClEls component
#include <mcuxClExample_ELS_Helper.h>

#define CEILING(x,y)  (((x) + (y) - 1U) / (y))
#define OUT_BUFFER_SIZE (MCUXCLRANDOMMODES_RESEED_INTERVAL_PTG3 * 2u)

static const uint32_t entropyInputInit[CEILING(MCUXCLRANDOMMODES_TESTMODE_CTR_DRBG_AES256_INIT_ENTROPY_SIZE, sizeof(uint32_t))] =
{
    /* Entropy for init (last byte is zero, because initSize is 71 bytes) */
    0xd871e6c9u, 0x45a82e7du, 0x26ef0940u, 0x80cb91b8u, 0x2e211226u, 0xd6416349u, 0x1b227780u, 0x14ef2f2eu,
    0xfdc37262u, 0x2db280b8u, 0x4808837au, 0xb6d5680bu, 0x54a9ec86u, 0x699cfaa2u, 0xdb9134d9u, 0xa3bcd0c9u,
    0x7e62a5dau, 0x00e08521u
};

static const uint32_t entropyInputGenerate[CEILING(MCUXCLRANDOMMODES_TESTMODE_CTR_DRBG_AES256_RESEED_ENTROPY_SIZE * 2u, sizeof(uint32_t))] =
{
    /* Entropy for first reseed at the beginning of the generate call (last byte is not used in first reseed, because reseedsize is 55) */
    0xe19793c3u, 0x336d3bedu, 0x32ea9ac4u, 0x56c2b89fu, 0xe90cd270u, 0x0146b0a4u, 0xb19a334au, 0x805f2e78u,
    0x1ae376eau, 0x46683dedu, 0x186c9b7bu, 0x682e6ea8u, 0x836d643du, 0x1f7356a2u,
    /* Entropy for second reseed after 32 generated bytes (last byte from first reseed is used, two last bytes from this reseed are not used and set to zero, because reseedsize is 55) */
    0xc437f850u, 0x8238cd74u, 0x9812eb32u, 0x9859fc43u, 0x528daf05u, 0x3c4c0016u, 0x18c5bb22u, 0xd0703bf9u,
    0xa5fd78e5u, 0x888a413au, 0xc818c52eu, 0xee4058ebu, 0xe62274e3u, 0x0000fe64u
};

/* Reference output is generated by running this example */
static const uint8_t refOutput[OUT_BUFFER_SIZE] =
{
    0x68u, 0xEDu, 0x61u, 0x34u, 0x2Fu, 0x1Cu, 0x39u, 0x9Eu,
    0xA0u, 0xC9u, 0x1Bu, 0x79u, 0x17u, 0x6Fu, 0x35u, 0x09u,
    0xA1u, 0xD1u, 0x45u, 0xD5u, 0xEFu, 0xD5u, 0x83u, 0xD1u,
    0xCCu, 0x01u, 0x30u, 0x13u, 0xEFu, 0xFAu, 0x1Au, 0x19u,
    0x22u, 0xD5u, 0xA3u, 0x49u, 0x85u, 0x70u, 0xA7u, 0xE5u,
    0xA9u, 0x32u, 0x4Bu, 0xA5u, 0x90u, 0x9Fu, 0x99u, 0x53u,
    0x4Du, 0x38u, 0x35u, 0xC9u, 0xF8u, 0xCFu, 0x61u, 0xC3u,
    0xF1u, 0x67u, 0xFDu, 0x8Bu, 0xC3u, 0x13u, 0x1Du, 0x02u
};

/** Performs an example usage of the mcuxClRandom and mcuxClRandomModes components with test mode.
 * @retval true  The example code completed successfully
 * @retval false The example code failed */
MCUXCLEXAMPLE_FUNCTION(mcuxClRandomModes_TestMode_CtrDrbg_AES256_PTG3_example)
{
    /**************************************************************************/
    /* Preparation                                                            */
    /**************************************************************************/

    /** Initialize ELS, Enable the ELS **/
    if(!mcuxClExample_Els_Init(MCUXCLELS_RESET_DO_NOT_CANCEL))
    {
        return MCUXCLEXAMPLE_ERROR;
    }

    mcuxClSession_Descriptor_t sessionDesc;
    mcuxClSession_Handle_t session = &sessionDesc;
    MCUXCLEXAMPLE_ALLOCATE_AND_INITIALIZE_SESSION(session, MCUXCLRANDOMMODES_MAX_CPU_WA_BUFFER_SIZE, 0u);

    /* Allocate space for a test mode descriptor for an AES-256 CTR_DRBG PTG3. */
    uint32_t testModeDescBytes[(MCUXCLRANDOMMODES_TESTMODE_DESCRIPTOR_SIZE + sizeof(uint32_t) - 1U)/sizeof(uint32_t)];
    mcuxClRandom_ModeDescriptor_t *pTestModeDesc = (mcuxClRandom_ModeDescriptor_t *) testModeDescBytes;


    /**************************************************************************/
    /* Test mode creation and for an AES-256 CTR_DRBG PTG3 and preparation    */
    /* of known entropy input for later DRBG instantiation                    */
    /**************************************************************************/
    MCUX_CSSL_FP_FUNCTION_CALL_BEGIN(cp_status, cp_token, mcuxClRandomModes_createTestFromNormalMode(
                                        pTestModeDesc,
                                        mcuxClRandomModes_Mode_CtrDrbg_AES256_PTG3,
                                        entropyInputInit
                                   ));

    if((MCUX_CSSL_FP_FUNCTION_CALLED(mcuxClRandomModes_createTestFromNormalMode) != cp_token) || (MCUXCLRANDOM_STATUS_OK != cp_status))
    {
        return MCUXCLEXAMPLE_ERROR;
    }
    MCUX_CSSL_FP_FUNCTION_CALL_END();


    /**************************************************************************/
    /* Test mode initialization with known entropy input                      */
    /**************************************************************************/
    uint32_t context[MCUXCLRANDOMMODES_CTR_DRBG_AES256_CONTEXT_SIZE_IN_WORDS] = {0};
    
    MCUX_CSSL_FP_FUNCTION_CALL_BEGIN(ri_status, init_token, mcuxClRandom_init(
                                        session,
                                        (mcuxClRandom_Context_t)context,
                                        pTestModeDesc
                                   ));

    if((MCUX_CSSL_FP_FUNCTION_CALLED(mcuxClRandom_init) != init_token) || (MCUXCLRANDOM_STATUS_OK != ri_status))
    {
        return MCUXCLEXAMPLE_ERROR;
    }
    MCUX_CSSL_FP_FUNCTION_CALL_END();


    /**************************************************************************/
    /* Generate 64 random bytes. This will reseed the DRBG with known entropy */
    /* twice, once at the beginning of the generate call and once after 32    */
    /* generated bytes                                                        */
    /**************************************************************************/

    /* Update entropy input to be taken for the upcoming reseeding in generate */
    MCUX_CSSL_FP_FUNCTION_CALL_BEGIN(ue_status, ue_token, mcuxClRandomModes_updateEntropyInput(pTestModeDesc, entropyInputGenerate));

    if((MCUX_CSSL_FP_FUNCTION_CALLED(mcuxClRandomModes_updateEntropyInput) != ue_token) || (MCUXCLRANDOM_STATUS_OK != ue_status))
    {
        return MCUXCLEXAMPLE_ERROR;
    }
    MCUX_CSSL_FP_FUNCTION_CALL_END();

    /* Generate random bytes. */
    uint8_t outBuffer[OUT_BUFFER_SIZE] = {0u};
    MCUX_CSSL_FP_FUNCTION_CALL_BEGIN(generate_status, generate_token, mcuxClRandom_generate(
                                        session,
                                        outBuffer,
                                        OUT_BUFFER_SIZE
                                   ));

    if((MCUX_CSSL_FP_FUNCTION_CALLED(mcuxClRandom_generate) != generate_token) || (MCUXCLRANDOM_STATUS_OK != generate_status))
    {
      return MCUXCLEXAMPLE_ERROR;
    }
    MCUX_CSSL_FP_FUNCTION_CALL_END();


    /**************************************************************************/
    /* Compare the last generated random output to the expected output        */
    /**************************************************************************/
    
    bool outputIsExpected = mcuxClCore_assertEqual((const uint8_t *) outBuffer, (const uint8_t*) refOutput, OUT_BUFFER_SIZE);

    /* Return error if buffers are unequal */
    if(!outputIsExpected)
    {
      return MCUXCLEXAMPLE_ERROR;
    }


    /**************************************************************************/
    /* Cleanup                                                                */
    /**************************************************************************/

    /* Random uninit. */
    MCUX_CSSL_FP_FUNCTION_CALL_BEGIN(ru_status, uninit_token, mcuxClRandom_uninit(session));

    if((MCUX_CSSL_FP_FUNCTION_CALLED(mcuxClRandom_uninit) != uninit_token) || (MCUXCLRANDOM_STATUS_OK != ru_status))
    {
      return MCUXCLEXAMPLE_ERROR;
    }
    MCUX_CSSL_FP_FUNCTION_CALL_END();

    /** Destroy Session and cleanup Session **/
    if(!mcuxClExample_Session_Clean(session))
    {
        return MCUXCLEXAMPLE_ERROR;
    }

    /** Disable the ELS **/
    if(!mcuxClExample_Els_Disable())
    {
        return MCUXCLEXAMPLE_ERROR;
    }

    return MCUXCLEXAMPLE_OK;
}
